### PR TITLE
Some improvements to speed up my workflow

### PR DESCRIPTION
**Pull request by verkel**
Hi,

I'm using your app to plan some SNES beadsprites. It's working great -- thank you for taking the time to create the program. :) Reading which color was which from the bead sheet image wasn't as fast as I would've liked, though. So seeing this was open source, I decided to extend the app to display the selected color in the final image preview. Also I made the Load chain dialog to remember where it last was.

If you like my changes, feel free to include them verbatim or modified as you like. In particular, ColorInfoImageDisplay depending on the AbstractReduceColorsFilter to get the palette doesn't feel like the cleanest thing, but it seemed the current palette is stored there, so I guess it works OK.

### CODE REVIEW

**Comment by dolkow** [comment]
Looks great, thanks!

**Comment by dolkow** [comment]
I'll try to get a new release out some time this week. If it's not out by Saturday evening, feel free to nag me. :)

**Comment by verkel** [comment]
You're welcome. :)

**Comment by dolkow** [comment]
Release is now live on the website! :)

**Comment by verkel** [comment]
Nice! There seems to be a small problem with the auto updater though, even with this latest version it now notifies that there's a new release, and asks whether you want to download it. About dialog still says v. 2010-10-24-1032, perhaps it's comparing this to version info from the update server?

**Comment by dolkow** [comment]
Yeah, the "version" file apparently needs to be updated manually. I think I added that so that people wouldn't get update notifications for added translations -- guess it came back to bite me now. :)

I've uploaded a new JAR which should fix the problem.

**Pull request merged**
